##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sqccltobn6ax/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R elements.html $DEPLOYPATH
    - /bin/cp -R generic.html $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH